services:
  cache:
    container_name: valkey
    hostname: valkey
    image: valkey/valkey:7.2.6
    volumes:
      - ./conf/valkey.conf:/etc/valkey/valkey.conf
      - ./data:/data
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - chess

  datasource:
    container_name: chess-history
    image: postgres:16.0
    env_file:
      - infrastructure.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - chess
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chess:
    driver: bridge

volumes:
  postgres:
  pgadmin: