services:
  postgres:
    container_name: chess
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fdiopm1297te7
      POSTGRES_DB: library
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: