services:
  chessland:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
    depends_on:
      - datasource
    networks:
      - chess

  datasource:
    container_name: chess
    image: postgres:16.0
    env_file:
      - infrastructure.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - chess
    restart: unless-stopped

  datasource-administration:
    container_name: chessadministration
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - chess
    restart: unless-stopped

networks:
  chess:
    driver: bridge

volumes:
  postgres:
  pgadmin: